expr: test LSTMNet

device: cuda:1

data:
  dataset: welding
  mode: test

model:
  name: LSTMNet

hyperparams:
  batch_size: 2

save_weights_dir: saved/
weights_file_name: lstmnet.welding.100epochs.pth