expr: train DNN

device: cuda:1

data:
  dataset: welding
  mode: train

model:
  name: DNN

hyperparams:
  optim: AdamW
  lr: 0.0001
  weight_decay: 0.001
  epochs: 1000
  batch_size: 8

loss_fn: mse_loss

save_path: saved